__title__ = "fastcrc"
__description__ = "A hyper-fast Python module for computing CRC checksum"
__url__ = "https://github.com/overcat/fastcrc"
__issues__ = f"{__url__}/issues"
__version__ = "0.1.0"
__author__ = "overcat"
__author_email__ = "4catcode@gmail.com"
__license__ = "MIT License"
